http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec:
          enabled: true
          crowdsecAppsecEnabled: false
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: IofQADUvULiUo/njZjxTg8mYZk18mlYwe1b8XlOJSV0
          crowdsecMode: stream
